spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blueprint
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.yml
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
blueprint:
  salt: 123
  pepper: 345
