name: ci-release
on:
  release:
    types:
    - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: generate release notes
      run: |
        echo ${GITHUB_REF}
        TAG=${GITHUB_REF/refs\/tags\/}
        echo ${TAG}
        npx github-release-notes release --override --tags ${TAG}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
