name: ci
on:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-jdk-11
    steps:
    - uses: actions/checkout@v2
    - run: mvn --batch-mode package
    - uses: actions/upload-artifact@v1
      with:
        name: api
        path: api/target
    - uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/target
  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: app
        path: app/target
    - run: ls && ls app
    - run: docker build .
